[package]
name = "rinex-cli"
version = "0.12.1"
license = "MPL-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "RINEX and SP3 data post processing tool"
homepage = "https://github.com/rtk-rs"
repository = "https://github.com/rtk-rs/rinex-cli"
keywords = ["geo", "gps", "rinex", "galileo", "timing"]
categories = [
    "science",
    "science::geo",
    "command-line-interface",
    "command-line-utilities",
]
edition = "2021"
readme = "README.md"
rust-version = "1.64"

[dependencies]
log = "0.4"
walkdir = "2.4.0"
geo-types = "0.7.11"
env_logger = "0.11"
serde_json = "1"
lazy_static = "1.4"
thiserror = "2"
itertools = "0.14"
map_3d = "0.1.5"

maud = "0.27"
plotly = "0.9"

clap = { version = "4.4.13", features = ["derive", "color"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }

kml = { version = "0.8.6", optional = true }
gpx = { version = "0.10", optional = true }
csv = { version = "1.3.0", optional = true }

anise = { version = "0.5.3", features = ["embed_ephem"] }
hifitime = { version = "4.0", features = ["serde", "std"] }

gnss-rs = { version = "2.3.5", features = ["serde"] }
gnss-qc = { git = "https://github.com/rtk-rs/gnss-qc", branch = "main", features = ["sp3"] } 

sp3 = { git = "https://github.com/rtk-rs/sp3", branch = "main", features = ["processing", "anise", "flate2", "serde"] }

rinex = { git = "https://github.com/rtk-rs/rinex", branch = "main",  features = ["obs", "nav", "ionex", "antex", "clock", "flate2", "processing", "serde"] }

gnss-rtk = { git = "https://github.com/rtk-rs/gnss-rtk", branch = "nav_x4", features = ["serde"] }
# gnss-rtk = { path = "../gnss-rtk", features = ["serde"] }

cggtts = { version = "4.2.0", features = ["serde", "scheduler"], optional = true }
