name: Benchmarking

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarking:
    name: Daily Results
    runs-on: ubuntu-latest
    env:
      CARGO: cargo
      RUST_BACKTRACE: 1
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build
        run: cargo build --all-features -r

      - name: Galileo BRDC (+CPP)
        run: |
            ./target/release/rinex-cli \
                -f -q \
                -P "Gal;C1C,C5Q" \
                --fp data/CRNX/V3/MOJN00DNK_R_20201770000_01D_30S_MO.crx.gz \
                --fp data/NAV/V3/MOJN00DNK_R_20201770000_01D_MN.rnx.gz \
                ppp -c examples/CONFIG/CPP/basic.json |
                tee cggtts_brdc_cpp_mojn_e1e5.logs

      - name: Galileo BRDC (+CPP) (+CGGTTS)
        run: |
            ./target/release/rinex-cli \
                -f -q \
                -P "Gal;C1C,C5Q" \
                --fp data/CRNX/V3/MOJN00DNK_R_20201770000_01D_30S_MO.crx.gz \
                --fp data/NAV/V3/MOJN00DNK_R_20201770000_01D_MN.rnx.gz \
                ppp --cggtts -c examples/CONFIG/CPP/basic.json |
                tee cggtts_brdc_cpp_mojn_e1e5.logs
      
      - name: Upload results
        run: |
            ls -l
            ls -l WORKSPACE/*
